# Generated by Django 5.2.8 on 2025-11-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
